name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker image build -t mppbar:latest .

    # - name: Prepare coverage
    #   run: |
    #     ID=$(docker create mppbar)
    #     docker cp $ID:/code/target/reports/mppbar_coverage.xml mppbar_coverage.xml
    #     sed -i -e 's,filename="mppbar/,filename="src/main/python/mppbar/,g' mppbar_coverage.xml

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: mppbar_coverage.xml